# Generated by Django 5.0.4 on 2024-05-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='start_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
