# Generated by Django 5.0.4 on 2024-04-28 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='task_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='usersubtask',
            old_name='subtask',
            new_name='subtask_id',
        ),
        migrations.RenameField(
            model_name='usersubtask',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='subtask',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='subtask_name',
            field=models.CharField(default='any value', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='#223344', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usersubtask',
            unique_together={('user_id', 'subtask_id')},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('subtask_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.subtask')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.project')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.user')),
            ],
        ),
    ]
