# Generated by Django 5.0.4 on 2024-05-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_rename_task_subtask_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('member', 'member')], default='member', max_length=50),
            preserve_default=False,
        ),
    ]
