# Generated by Django 5.0.4 on 2024-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_alter_subtask_description_alter_subtask_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='active', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='string', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='string', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('inactive', 'inactive'), ('active', 'active')], default='string', max_length=8),
            preserve_default=False,
        ),
    ]
